#!/usr/bin/sh

device=$(ls /sys/class/leds | grep scrolllock | head -n1)

brillo=$(brightnessctl info -d $device | grep "1")

line=$(echo $brillo | grep "Current")

if [[ -z $line ]]; then
	brightnessctl s 1 -d $device &> /dev/null
else
	brightnessctl s 0 -d $device &> /dev/null
fi
